/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed.onboarding'
import { Route as AuthedAdvancedOnboardingRouteImport } from './routes/_authed.advanced-onboarding'
import { Route as AuthedAdsIndexRouteImport } from './routes/_authed.ads.index'
import { Route as AuthedAdsNewRouteImport } from './routes/_authed.ads.new'
import { Route as AuthedAdsAdIdRouteImport } from './routes/_authed.ads.$adId'
import { Route as AuthedAdminSeedRouteImport } from './routes/_authed.admin.seed'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdvancedOnboardingRoute =
  AuthedAdvancedOnboardingRouteImport.update({
    id: '/advanced-onboarding',
    path: '/advanced-onboarding',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdsIndexRoute = AuthedAdsIndexRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdsNewRoute = AuthedAdsNewRouteImport.update({
  id: '/ads/new',
  path: '/ads/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdsAdIdRoute = AuthedAdsAdIdRouteImport.update({
  id: '/ads/$adId',
  path: '/ads/$adId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminSeedRoute = AuthedAdminSeedRouteImport.update({
  id: '/admin/seed',
  path: '/admin/seed',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/advanced-onboarding': typeof AuthedAdvancedOnboardingRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/admin/seed': typeof AuthedAdminSeedRoute
  '/ads/$adId': typeof AuthedAdsAdIdRoute
  '/ads/new': typeof AuthedAdsNewRoute
  '/ads': typeof AuthedAdsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/advanced-onboarding': typeof AuthedAdvancedOnboardingRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/admin/seed': typeof AuthedAdminSeedRoute
  '/ads/$adId': typeof AuthedAdsAdIdRoute
  '/ads/new': typeof AuthedAdsNewRoute
  '/ads': typeof AuthedAdsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/ai-chat': typeof AiChatRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/_authed/advanced-onboarding': typeof AuthedAdvancedOnboardingRoute
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/admin/seed': typeof AuthedAdminSeedRoute
  '/_authed/ads/$adId': typeof AuthedAdsAdIdRoute
  '/_authed/ads/new': typeof AuthedAdsNewRoute
  '/_authed/ads/': typeof AuthedAdsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-chat'
    | '/profile'
    | '/sign-in'
    | '/subscriptions'
    | '/advanced-onboarding'
    | '/onboarding'
    | '/admin/seed'
    | '/ads/$adId'
    | '/ads/new'
    | '/ads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-chat'
    | '/profile'
    | '/sign-in'
    | '/subscriptions'
    | '/advanced-onboarding'
    | '/onboarding'
    | '/admin/seed'
    | '/ads/$adId'
    | '/ads/new'
    | '/ads'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/ai-chat'
    | '/profile'
    | '/sign-in'
    | '/subscriptions'
    | '/_authed/advanced-onboarding'
    | '/_authed/onboarding'
    | '/_authed/admin/seed'
    | '/_authed/ads/$adId'
    | '/_authed/ads/new'
    | '/_authed/ads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AiChatRoute: typeof AiChatRoute
  ProfileRoute: typeof ProfileRoute
  SignInRoute: typeof SignInRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/advanced-onboarding': {
      id: '/_authed/advanced-onboarding'
      path: '/advanced-onboarding'
      fullPath: '/advanced-onboarding'
      preLoaderRoute: typeof AuthedAdvancedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ads/': {
      id: '/_authed/ads/'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AuthedAdsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ads/new': {
      id: '/_authed/ads/new'
      path: '/ads/new'
      fullPath: '/ads/new'
      preLoaderRoute: typeof AuthedAdsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ads/$adId': {
      id: '/_authed/ads/$adId'
      path: '/ads/$adId'
      fullPath: '/ads/$adId'
      preLoaderRoute: typeof AuthedAdsAdIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/seed': {
      id: '/_authed/admin/seed'
      path: '/admin/seed'
      fullPath: '/admin/seed'
      preLoaderRoute: typeof AuthedAdminSeedRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdvancedOnboardingRoute: typeof AuthedAdvancedOnboardingRoute
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedAdminSeedRoute: typeof AuthedAdminSeedRoute
  AuthedAdsAdIdRoute: typeof AuthedAdsAdIdRoute
  AuthedAdsNewRoute: typeof AuthedAdsNewRoute
  AuthedAdsIndexRoute: typeof AuthedAdsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdvancedOnboardingRoute: AuthedAdvancedOnboardingRoute,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedAdminSeedRoute: AuthedAdminSeedRoute,
  AuthedAdsAdIdRoute: AuthedAdsAdIdRoute,
  AuthedAdsNewRoute: AuthedAdsNewRoute,
  AuthedAdsIndexRoute: AuthedAdsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AiChatRoute: AiChatRoute,
  ProfileRoute: ProfileRoute,
  SignInRoute: SignInRoute,
  SubscriptionsRoute: SubscriptionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
