/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsCustomAgentsRouteImport } from './routes/settings/custom-agents'
import { Route as CanvasCanvasIdIndexRouteImport } from './routes/canvas/$canvasId/index'
import { Route as CanvasCanvasIdChatRouteImport } from './routes/canvas/$canvasId/chat'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCustomAgentsRoute = SettingsCustomAgentsRouteImport.update({
  id: '/settings/custom-agents',
  path: '/settings/custom-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasCanvasIdIndexRoute = CanvasCanvasIdIndexRouteImport.update({
  id: '/canvas/$canvasId/',
  path: '/canvas/$canvasId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasCanvasIdChatRoute = CanvasCanvasIdChatRouteImport.update({
  id: '/canvas/$canvasId/chat',
  path: '/canvas/$canvasId/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/settings/custom-agents': typeof SettingsCustomAgentsRoute
  '/canvas/$canvasId/chat': typeof CanvasCanvasIdChatRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/settings/custom-agents': typeof SettingsCustomAgentsRoute
  '/canvas/$canvasId/chat': typeof CanvasCanvasIdChatRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRoute
  '/pricing': typeof PricingRoute
  '/settings/custom-agents': typeof SettingsCustomAgentsRoute
  '/canvas/$canvasId/chat': typeof CanvasCanvasIdChatRoute
  '/canvas/$canvasId/': typeof CanvasCanvasIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/settings/custom-agents'
    | '/canvas/$canvasId/chat'
    | '/canvas/$canvasId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/settings/custom-agents'
    | '/canvas/$canvasId/chat'
    | '/canvas/$canvasId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/pricing'
    | '/settings/custom-agents'
    | '/canvas/$canvasId/chat'
    | '/canvas/$canvasId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRoute
  PricingRoute: typeof PricingRoute
  SettingsCustomAgentsRoute: typeof SettingsCustomAgentsRoute
  CanvasCanvasIdChatRoute: typeof CanvasCanvasIdChatRoute
  CanvasCanvasIdIndexRoute: typeof CanvasCanvasIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/custom-agents': {
      id: '/settings/custom-agents'
      path: '/settings/custom-agents'
      fullPath: '/settings/custom-agents'
      preLoaderRoute: typeof SettingsCustomAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/$canvasId/': {
      id: '/canvas/$canvasId/'
      path: '/canvas/$canvasId'
      fullPath: '/canvas/$canvasId'
      preLoaderRoute: typeof CanvasCanvasIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/$canvasId/chat': {
      id: '/canvas/$canvasId/chat'
      path: '/canvas/$canvasId/chat'
      fullPath: '/canvas/$canvasId/chat'
      preLoaderRoute: typeof CanvasCanvasIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRoute,
  PricingRoute: PricingRoute,
  SettingsCustomAgentsRoute: SettingsCustomAgentsRoute,
  CanvasCanvasIdChatRoute: CanvasCanvasIdChatRoute,
  CanvasCanvasIdIndexRoute: CanvasCanvasIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
